server:
  port: 9003

spring:
  application:
    name: gouwo-essay
  #  profiles:
  #    active: dev

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/gouwo?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root


  data:
    #mongodb配置========================
    mongodb:
      host: localhost # mongodb的连接地址
      port: 27017 # mongodb的连接端口号
      database: gouwo # mongodb的连接的数据库

    #elasticsearch配置========================
    elasticsearch:
      repositories:
        enabled: true
      cluster-nodes: 127.0.0.1:9300 # es的连接地址及端口号
      cluster-name: elasticsearch # es集群的名称

  #Redis配置========================
  redis:
    host: localhost # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: # Redis服务器连接密码（默认为空）

#    jedis:
#      pool:
#        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
#        max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
#        max-idle: 8 # 连接池中的最大空闲连接
#        min-idle: 0 # 连接池中的最小空闲连接

#    Jedis:非线程安全 vs Lettuce:线程安全

    lettuce:
      pool:
        max-active: 8 # 连接池最大连接数
        max-idle: 8 # 连接池最大空闲连接数
        min-idle: 0 # 连接池最小空闲连接数
        max-wait: -1ms # 连接池最大阻塞等待时间，负值表示没有限制
    timeout: 3000ms # 连接超时时间（毫秒）

  #文件上传配置========================
  servlet:
    multipart:
      enabled: true #开启文件上传
      max-file-size: 10MB #限制文件上传大小为10M


mybatis:
  mapper-locations:
    - classpath:dao/*.xml
    - classpath:mapper/*.xml


# MinIO对象存储相关配置=====================
minio:
  endpoint: http://172.17.0.2:9000 #MinIO服务所在地址
  bucketName: gouwo #存储桶名称
  accessKey: minioadmin #访问的key
  secretKey: minioadmin #访问的秘钥



eureka:
  client:
    service-url:
      defaultZone: http://localhost:8181/eureka/
    registry-fetch-interval-seconds: 10

