server:
  port: 9002

spring:
  application:
    name: gouwo-essay
  #  profiles:
  #    active: dev

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/gouwo?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root

  data:
    mongodb:
      host: localhost # mongodb的连接地址
      port: 27017 # mongodb的连接端口号
      database: gouwo # mongodb的连接的数据库


mybatis:
  mapper-locations:
    - classpath:mapper/*.xml



eureka:
  client:
    service-url:
      defaultZone: http://localhost:8181/eureka/
    registry-fetch-interval-seconds: 10

