server:
  port: 9000

spring:
  application:
    name: gouwo-people
#  profiles:
#    active: dev

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/gouwo?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root


mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
#mybatis-plus:
#  mapper-locations: classpath*:mapper/*
#feign:
#  hystrix:
#    # 开启Feign的Hystrix熔断器支持
#    enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8181/eureka/
    registry-fetch-interval-seconds: 10

