server:
  port: 8281
spring:
  application:
    name: gouwo-config
  profiles:
    active: native #使用本地配置，要使用git存储改为git即可
  cloud:
    config:
      server:
        native: #本地仓库存储
          search-locations: classpath:/config/{application}
        git: #Git仓库存储
          uri: https://github.com/askyc/gouwo-config.git
          username: asky
          password: 123456
          clone-on-start: true
          search-paths: '{application}'
