server:
  port: 8581
spring:
  application:
    name: gouwo-turbine
  profiles:
    active: dev

turbine:
  aggregator:
    clusterConfig: default #指定聚合哪些集群，多个使用”,”分割，默认为default
  appConfig: gouwo-gateway #配置Eureka中的serviceId列表，表明监控哪些服务
  #clusterNameExpression: new String("default") #设置监控的表达式，通过此表达式表示要获取监控信息名称
  combine-host-port: true #以主机名和端口号来区分服务


#===================================================================
#访问打开： http://localhost:8581/hystrix
#输入：http://localhost:8581/actuator/hystrix.stream